# credentials.http
#
# Requests for managing centrally stored cloud provider credentials.
# These credentials are used as a fallback when a job submission
# does not include its own specific credentials.
#
# Variables - set these for your environment
@hostname = http://localhost:8081
@api_v1 = {{hostname}}/api/v1

###
# @name SaveS3Credentials
POST {{api_v1}}/credentials/s3
Content-Type: application/json

{
  "access_key_id": "YOUR_AWS_ACCESS_KEY_ID",
  "secret_access_key": "YOUR_AWS_SECRET_ACCESS_KEY"
}


###
# @name SaveR2Credentials
POST {{api_v1}}/credentials/r2
Content-Type: application/json

{
  "access_key_id": "YOUR_GLOBAL_R2_ACCESS_KEY_ID",
  "secret_access_key": "YOUR_GLOBAL_R2_SECRET_ACCESS_KEY"
}


###
# @name SaveGCSCredentials
POST {{api_v1}}/credentials/gcs
Content-Type: application/json

{
  "service_account_json": "YOUR_GCS_SERVICE_ACCOUNT_JSON_STRING"
}


###
# @name SaveAzureCredentials
POST {{api_v1}}/credentials/azure
Content-Type: application/json

{
  "sas_token": "YOUR_AZURE_SAS_TOKEN"
}


###
# @name SaveSFTPCredentialsPassword
POST {{api_v1}}/credentials/sftp
Content-Type: application/json

{
  "user": "sftp_user",
  "password": "YOUR_SFTP_PASSWORD",
  "host": "sftp.example.com",
  "port": 22
}


###
# @name SaveSFTPCredentialsKey
POST {{api_v1}}/credentials/sftp
Content-Type: application/json

{
  "user": "sftp_user_key",
  "private_key": "-----BEGIN OPENSSH PRIVATE KEY-----\\n...your key...\\n-----END OPENSSH PRIVATE KEY-----",
  "host": "sftp.example.com",
  "port": 2222
}
